// Define action types
export const GET_ACTIVITY= 'GET_ACTIVITY';
export const ADD_TO_ACTIVITY_LIST = 'ADD_TO_ACTIVITY_LIST';
export const REMOVE_FROM_ACTIVITY_LIST = 'REMOVE_FROM_ACTIVITY_LIST';
export const CLEAR_DATA = 'CLEAR_DATA';
export const USERS_DATA_STATE_CHANGE = 'USERS_DATA_STATE_CHANGE';
export const USERS_ACTIVITY_STATE_CHANGE = 'USERS_ACTIVITY_STATE_CHANGE';
export const USER_STATE_CHANGE = 'USER_STATE_CHANGE';
